### ISSUE TITLE
Я сойду с ума

### ISSUE THREAD

**Issue by Kudiny4** [Kudiny4/Exercises#1]
Проверь у себя. Не могу понять почему, когда условие выполняется, он не идет внутрь этого модуля (не пишет Incorrect и не запрашивает слово заново), а сразу переходит к else, будто условие не выполнилось.

**Comment by Kudiny4** [comment]
В итоге верно вот так:
while True:
    num = int(input('Введите число от 0 до 10'))
    if num > 0 and num < 10:
        print ('Correct')
        break
    else:
        print('Incorrect')

**Comment by dpolevodin** [comment]
Don't worry, be happy)
